# Generated by Django 3.2.9 on 2021-11-02 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_otraclase'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OtraClase',
        ),
    ]
