# Generated by Django 3.2.9 on 2021-11-02 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0003_delete_otraclase'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Productos',
            new_name='Producto',
        ),
        migrations.AlterModelTable(
            name='producto',
            table='productos',
        ),
    ]
