# Generated by Django 3.2.9 on 2021-11-18 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0005_tag'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='tag',
            table='tags',
        ),
    ]
