# Generated by Django 3.2.9 on 2021-11-18 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0006_alter_tag_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='tags',
            field=models.ManyToManyField(to='productos.Tag'),
        ),
    ]
